<a href="https://colab.research.google.com/github/Ris-code/LinearRegression--Diabetes/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import files
upload=files.upload()

Saving diabetes (1).csv to diabetes (1).csv


In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn import linear_model
from sklearn.utils import shuffle

data = pd.read_csv("diabetes (1).csv")

data = data[["Pregnancies","BloodPressure", "SkinThickness", "BMI", "DiabetesPedigreeFunction", "Age", "Outcome"]]

predict = "Age"

X = np.array(data.drop([predict], axis=1))
y = np.array(data[predict])

x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size = 0.1)

linear = linear_model.LinearRegression()

linear.fit(x_train, y_train)
acc = linear.score(x_test, y_test)
print(acc)
print(x_test)
print(y_test)
print('Coefficient: \n', linear.coef_)
print('Intercept: \n', linear.intercept_)

predictions = linear.predict(x_test)
print(predictions)

for x in range(len(predictions)):
    print(predictions[x], x_test[x], y_test[x])

0.2651132269256603
[[4.000e+00 7.800e+01 3.900e+01 3.700e+01 2.640e-01 1.000e+00]
 [2.000e+00 0.000e+00 0.000e+00 0.000e+00 3.040e-01 0.000e+00]
 [0.000e+00 8.800e+01 3.000e+01 3.250e+01 8.550e-01 1.000e+00]
 [6.000e+00 6.800e+01 4.100e+01 3.900e+01 7.270e-01 1.000e+00]
 [1.300e+01 6.000e+01 0.000e+00 3.280e+01 1.800e-01 0.000e+00]
 [3.000e+00 6.200e+01 2.400e+01 2.600e+01 2.230e-01 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 3.240e+01 1.410e-01 1.000e+00]
 [2.000e+00 6.400e+01 2.400e+01 2.970e+01 3.700e-01 0.000e+00]
 [2.000e+00 6.200e+01 1.000e+01 2.530e+01 8.810e-01 0.000e+00]
 [1.000e+00 6.400e+01 3.200e+01 3.510e+01 6.920e-01 1.000e+00]
 [1.100e+01 7.600e+01 2.800e+01 3.330e+01 1.353e+00 1.000e+00]
 [2.000e+00 7.600e+01 3.700e+01 3.970e+01 2.150e-01 0.000e+00]
 [5.000e+00 5.400e+01 2.800e+01 3.400e+01 4.990e-01 0.000e+00]
 [0.000e+00 6.000e+01 0.000e+00 3.530e+01 2.630e-01 0.000e+00]
 [6.000e+00 7.200e+01 3.200e+01 3.770e+01 3.240e-01 0.000e+00]
 [1.000e+00 5.600e+01 1.100e+01 2.25