<a href="https://colab.research.google.com/github/Ris-code/LinearRegression--Diabetes/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import files
upload=files.upload()

Saving diabetes (1).csv to diabetes (1).csv


In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn import linear_model
from sklearn.utils import shuffle

data = pd.read_csv("diabetes (1).csv")

data = data[["Pregnancies","BloodPressure", "SkinThickness", "BMI", "DiabetesPedigreeFunction", "Age", "Outcome"]]

predict = "Age"

X = np.array(data.drop([predict], axis=1))
y = np.array(data[predict])

x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size = 0.1)

linear = linear_model.LinearRegression()

linear.fit(x_train, y_train)
acc = linear.score(x_test, y_test)
print(acc)
print(x_test)
print('Coefficient: \n', linear.coef_)
print('Intercept: \n', linear.intercept_)

predictions = linear.predict(x_test)
print(predictions)

for x in range(len(predictions)):
    print(predictions[x], x_test[x], y_test[x])

0.42820736743945875
[[0.00e+00 6.60e+01 4.00e+01 3.43e+01 1.96e-01 1.00e+00]
 [2.00e+00 7.00e+01 1.70e+01 2.73e+01 8.50e-02 0.00e+00]
 [1.00e+00 4.60e+01 1.90e+01 2.87e+01 6.54e-01 0.00e+00]
 [1.00e+00 7.20e+01 3.00e+01 3.08e+01 8.21e-01 0.00e+00]
 [7.00e+00 7.00e+01 3.30e+01 2.55e+01 1.61e-01 0.00e+00]
 [2.00e+00 7.00e+01 1.60e+01 2.04e+01 2.35e-01 0.00e+00]
 [8.00e+00 7.60e+01 0.00e+00 2.78e+01 2.37e-01 0.00e+00]
 [2.00e+00 5.00e+01 2.30e+01 3.04e+01 9.68e-01 0.00e+00]
 [4.00e+00 8.60e+01 3.10e+01 2.80e+01 4.19e-01 0.00e+00]
 [1.00e+00 6.00e+01 3.70e+01 3.72e+01 5.09e-01 0.00e+00]
 [0.00e+00 8.00e+01 3.10e+01 4.52e+01 8.90e-02 0.00e+00]
 [5.00e+00 7.40e+01 1.80e+01 3.36e+01 9.97e-01 0.00e+00]
 [8.00e+00 7.40e+01 3.80e+01 2.59e+01 1.62e-01 0.00e+00]
 [0.00e+00 5.80e+01 2.00e+01 2.64e+01 3.52e-01 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 3.23e+01 8.39e-01 1.00e+00]
 [2.00e+00 5.80e+01 2.40e+01 2.77e+01 1.60e+00 0.00e+00]
 [8.00e+00 1.00e+02 3.60e+01 4.33e+01 2.39e-01 1.00e+00]
 [2.00e+00 