<a href="https://colab.research.google.com/github/Ris-code/LinearRegression--Diabetes/blob/main/ML_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
upload=files.upload()

Saving diabetes (1).csv to diabetes (1).csv


In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn import linear_model
from sklearn.utils import shuffle

data = pd.read_csv("diabetes (1).csv")

data = data[["Pregnancies","BloodPressure", "SkinThickness", "BMI", "DiabetesPedigreeFunction", "Age", "Outcome"]]

predict = "Age"

X = np.array(data.drop([predict], axis=1))
y = np.array(data[predict])

x_train, x_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size = 0.1)

linear = linear_model.LinearRegression()

linear.fit(x_train, y_train)
acc = linear.score(x_test, y_test)
print(acc)
print(x_test)
print(y_test)
print('Coefficient: \n', linear.coef_)
print('Intercept: \n', linear.intercept_)

predictions = linear.predict(x_test)
print(predictions)

for x in range(len(predictions)):
    print(predictions[x], x_test[x], y_test[x])

0.358052809785088
[[0.000e+00 8.200e+01 3.100e+01 3.820e+01 2.330e-01 0.000e+00]
 [7.000e+00 7.400e+01 2.600e+01 2.600e+01 6.470e-01 0.000e+00]
 [4.000e+00 6.400e+01 0.000e+00 2.890e+01 1.260e-01 0.000e+00]
 [4.000e+00 8.200e+01 1.800e+01 3.250e+01 2.350e-01 1.000e+00]
 [1.300e+01 7.000e+01 0.000e+00 3.420e+01 2.510e-01 0.000e+00]
 [6.000e+00 7.400e+01 1.800e+01 2.990e+01 7.220e-01 1.000e+00]
 [1.100e+01 8.400e+01 4.000e+01 4.680e+01 9.250e-01 1.000e+00]
 [1.000e+00 7.400e+01 0.000e+00 3.680e+01 8.800e-02 1.000e+00]
 [0.000e+00 7.000e+01 3.700e+01 3.940e+01 6.050e-01 0.000e+00]
 [1.000e+00 7.200e+01 0.000e+00 3.900e+01 1.222e+00 1.000e+00]
 [0.000e+00 6.500e+01 0.000e+00 2.460e+01 6.600e-01 0.000e+00]
 [3.000e+00 7.200e+01 3.200e+01 3.720e+01 2.670e-01 0.000e+00]
 [9.000e+00 8.000e+01 3.700e+01 3.280e+01 9.600e-02 0.000e+00]
 [4.000e+00 6.800e+01 2.100e+01 3.310e+01 1.600e-01 0.000e+00]
 [1.200e+01 8.200e+01 4.300e+01 3.920e+01 5.280e-01 1.000e+00]
 [4.000e+00 7.000e+01 3.200e+01 3.310